redux-persistを利用してフォーム入力値を保持する
IZUMIRU/patternlab pull request #16
Opened 2020-03-29 11:49 UTC by IZUMIRU

close: #15

2020-04-06 15:53 UTC, IZUMIRU commented
だいぶ実装に時間がかかってしまいましたが、お手すきの際にレビューお願いいたします。

2020-04-10 08:33 UTC, piro0919 requested changes
- `package.json` が書き換わっているのが謎です、せめて別issue、別PRで上げましょう
- 分割代入が甘すぎます、もう一度全体を見返してください
- `redux-persist`の導入と、それに伴う実装は別PRのほうが理想的ですね、次からは気をつけましょー

2020-04-10 08:33 UTC, piro0919 commented on src/components/atoms/forms/Input/style.module.scss
> +  width: 30%;
[imo]

値イマイチですね
atomsに合ってない気がします

2020-04-10 08:33 UTC, piro0919 commented on src/containers/pages/AddTodo/index.tsx
> +const AddTodo: FC<{ dispatch: Dispatch }> = ({ dispatch }) => {
[must]hooksでいきましょう

2020-04-10 08:33 UTC, piro0919 commented on src/containers/pages/AddTodo/index.tsx
> +  const handleSubmit = (event: React.FormEvent<HTMLFormElement>): void => {
[must]こっちもhooksで

2020-04-10 08:33 UTC, piro0919 commented on src/containers/pages/AddTodo/index.tsx
> +    event.preventDefault();
[imo]

確かいらなかったような
ちょっと調べてみてください

2020-04-10 08:33 UTC, piro0919 commented on src/containers/pages/AddTodo/index.tsx
> +  const handleChange = (event: React.ChangeEvent<HTMLInputElement>): void => {
[must]hooksでー

2020-04-10 08:33 UTC, piro0919 commented on src/index.tsx
> +      <React.Fragment>
[must]不要ですね

2020-04-10 08:33 UTC, piro0919 commented on src/reducers/todo/index.ts
> +export interface State {
[must]

命名が微妙です
保守性をもう少し考慮してみてください

2020-04-10 08:33 UTC, piro0919 commented on src/reducers/todo/index.ts
> +  [text: string]: string;
[must]

値が曖昧すぎますね
もっと具体的に落とし込みましょう

2020-04-10 08:33 UTC, piro0919 commented on src/reducers/todo/index.ts
> +export const initialState: State = {};
[must] 型を直した後で、見合う初期値を与えるようにしてみてください

2020-04-23 17:17 UTC, IZUMIRU commented
コミット修正したはずが、日本語のままに気を付ける。

2020-04-23 17:17 UTC, IZUMIRU commented on src/containers/pages/AddTodo/index.tsx
> +const AddTodo: FC<{ dispatch: Dispatch }> = ({ dispatch }) => {
https://github.com/IZUMIRU/patternlab/pull/16/commits/d30a897f862460d3d5677c0975da717a11556b75 にて修正しました

2020-04-23 17:17 UTC, IZUMIRU commented on src/containers/pages/AddTodo/index.tsx
> +  const handleSubmit = (event: React.FormEvent<HTMLFormElement>): void => {
https://github.com/IZUMIRU/patternlab/pull/16/commits/d30a897f862460d3d5677c0975da717a11556b75 にて修正しました

2020-04-23 17:17 UTC, IZUMIRU commented on src/containers/pages/AddTodo/index.tsx
> +  const handleChange = (event: React.ChangeEvent<HTMLInputElement>): void => {
https://github.com/IZUMIRU/patternlab/pull/16/commits/d30a897f862460d3d5677c0975da717a11556b75 にて修正しました

2020-04-23 17:17 UTC, IZUMIRU commented on src/index.tsx
> +      <React.Fragment>
https://github.com/IZUMIRU/patternlab/pull/16/commits/63a11b61c243feffb65d063b12bb63058d24b53d にて修正しました

2020-04-23 17:18 UTC, IZUMIRU commented on src/reducers/todo/index.ts
> +export interface State {
https://github.com/IZUMIRU/patternlab/pull/16/commits/17233c62fbbc0a23baeb483f4f8dc1f638029cd5 にて修正しました

2020-04-23 17:18 UTC, IZUMIRU commented on src/reducers/todo/index.ts
> +  [text: string]: string;
https://github.com/IZUMIRU/patternlab/pull/16/commits/5ad299e6f5f1e90a23427f2ae767fd81d741cddc にて修正しました

2020-04-23 17:18 UTC, IZUMIRU commented on src/reducers/todo/index.ts
> +export const initialState: State = {};
https://github.com/IZUMIRU/patternlab/pull/16/commits/5ad299e6f5f1e90a23427f2ae767fd81d741cddc にて修正しました

2020-04-23 17:19 UTC, IZUMIRU commented on src/components/atoms/forms/Input/style.module.scss
> +  width: 30%;
https://github.com/IZUMIRU/patternlab/pull/16/commits/9e39e62249a1d197df39f0a4ac2cb1c5138ef50f にて修正しました。別途どこで幅調整するかは調べて実装します。

2020-04-23 17:21 UTC, IZUMIRU commented on src/containers/pages/AddTodo/index.tsx
> +    event.preventDefault();
https://github.com/IZUMIRU/patternlab/pull/16/commits/d30a897f862460d3d5677c0975da717a11556b75 にて修正しました。

>>> React では false を返してもデフォルトの動作を抑止することができません。明示的に preventDefault を呼び出す必要があります。例えば、プレーンな HTML では、「新しいページを開く」というリンクのデフォルト動作を抑止するために次のように書くことができます。

2020-04-24 13:28 UTC, piro0919 commented on src/containers/pages/AddTodo/index.tsx
> +export default connect()(AddTodo);
[must]connect不要ですね

2020-04-24 13:28 UTC, piro0919 commented on src/containers/pages/AddTodo/index.tsx
> +  const handleSubmit = useCallback(() => dispatch(addTodo(value)), [
[imo]型引数ほしいです

2020-04-24 13:28 UTC, piro0919 commented on src/reducers/todo/index.ts
> +export interface todoState {
[must]命名がTSの規約から外れてますね

2020-04-24 13:28 UTC, piro0919 commented on src/reducers/todo/index.ts
> +  { type, payload }: AddTodoType
[must]
型があってないですね
reducerの挙動をもう少し確認してみましょう

2020-04-24 13:29 UTC, piro0919 requested changes
> package.json が書き換わっているのが謎です、せめて別issue、別PRで上げましょう
> 分割代入が甘すぎます、もう一度全体を見返してください

上記が直ってないですね

2020-04-25 02:56 UTC, IZUMIRU commented on src/containers/pages/AddTodo/index.tsx
> +  const handleSubmit = useCallback(() => dispatch(addTodo(value)), [
```
function useCallback<T extends (...args: any[]) => any>(callback: T, deps: DependencyList): T;
```

2020-04-25 03:07 UTC, IZUMIRU commented on src/containers/pages/AddTodo/index.tsx
> +  const handleSubmit = useCallback(() => dispatch(addTodo(value)), [
https://github.com/IZUMIRU/patternlab/pull/16/commits/e527367e5545f30a09108f2734b947bf325c7141 にて修正

2020-04-25 03:08 UTC, IZUMIRU commented on src/containers/pages/AddTodo/index.tsx
> +export default connect()(AddTodo);
https://github.com/IZUMIRU/patternlab/pull/16/commits/8866fd83f7763dd0174426b09d8b05ee7b36ab0f にて修正しました

2020-04-25 03:16 UTC, IZUMIRU commented on src/reducers/todo/index.ts
> +export interface todoState {
https://typescript-jp.gitbook.io/deep-dive/styleguide#intfsu

2020-04-25 03:20 UTC, IZUMIRU commented on src/reducers/todo/index.ts
> +export interface todoState {
https://github.com/IZUMIRU/patternlab/pull/16/commits/fc01bfbd6e13abaf2ab60b82908318a3c09bafc0 にて修正しました

2020-04-25 03:23 UTC, IZUMIRU commented
> package.json が書き換わっているのが謎です、せめて別issue、別PRで上げましょう

https://github.com/IZUMIRU/patternlab/pull/16/commits/8e5ed523b561a757b8fdc34ad47741fde18ad0e8 にsて修正しました

2020-04-26 18:07 UTC, IZUMIRU commented
[memo] 以下のようには書けない。

```tsx
const handleChange = useCallback<
  (event: React.ChangeEvent<HTMLInputElement>) => void
>((event: { target: value }) => setTodo(value), []);
```

2020-04-29 14:07 UTC, IZUMIRU commented on src/reducers/todo/index.ts
> +  { type, payload }: AddTodoType
https://github.com/IZUMIRU/patternlab/pull/16/commits/3381cb60018f7837a3f7950006c019b0d39403c3 にて修正しました

2020-04-29 14:37 UTC, IZUMIRU commented
[memo] 分割代入の記述方法がおかしい？

```ts
const todo: (
  state: TodoState,
  {
    payload: { todo },
    type,
  }: AddTodoType
// TypeError: Cannot read property 'todo' of undefined
) => TodoState = (state = initialState, { type, payload: { todo } }) => {
  switch (type) {
    case ADD_TODO: {
      state = initialState;
      // const { todo } = payload;
      return { ...state, todo };
    }
    default: {
      return state;
    }
  }
};
```

2020-04-29 15:39 UTC, IZUMIRU commented
根本解決ではないですが `payload` 削除して型まわり見直しました。恐縮ですが、スキル不足ゆえ理解できない部分が多々あるので、より踏み込んで指し示していただけると、幸いです。

2020-06-02 03:02 UTC, merged