Feat commitlint
IZUMIRU/patternlab pull request #2
Opened 2020-03-26 13:08 UTC by IZUMIRU

- https://github.com/conventional-changelog/commitlint

2020-03-26 15:35 UTC, piro0919 commented
こっちも PR のコメントが意味不明なので直しましょう

2020-03-26 15:39 UTC, IZUMIRU commented
```bash
$ git commit -m"fix: commitlint settings"

husky > commit-msg (node v10.16.0)
[feat_commitlint c992906] fix: commitlint settings
 2 files changed, 9 insertions(+), 3 deletions(-)
```

2020-03-26 16:03 UTC, piro0919 requested changes
[imo]バージョンは固定してインストールするようにしましょ。 🥇

2020-03-28 16:10 UTC, piro0919 approved these changes
LGTM 👍

2020-03-29 09:25 UTC, merged